[app]
log_level = "warn"
output = "./tmp/output/proof.txt"
clean_init_dbs = true

[db_commitment]
path = "./tmp/database/commitment.db"

[db_sbom]
path = "./tmp/database/sbom.db"

[db_vulnerability]
path = "./tmp/database/vulnerability.db"
