[app]
log_level = "warn"
output = "./tmp/output/proof.txt"
clean_init_dbs = false
# Checks if Rust dependencies in the SBOM are available on crates.io.
check_dependencies = false
check_dependencies_output = "./tmp/output/unfound_dependencies.log"

[db_commitment]
path = "./tmp/database/commitment.db"

[db_sbom]
path = "./tmp/database/sbom.db"

[db_dependency]
path = "./tmp/database/dependency.db"
