[app]
log_level = "debug"
output = "./tmp/output/proof.txt"

[db_commitment]
path = "./tmp/database/commitment.db"

[db_sbom]
path = "./tmp/database/sbom.db"

[db_vulnerability]
path = "./tmp/database/vulnerability.db"
