[sbom_database]
path = "./data/sbom.db"
host = ""
port = 0
user = ""
password = ""

[commitment_database]
path = "./data/commitment.db"
host = ""
port = 0
user = ""
password = ""

[app]
debug = true
log_level = "info"
